### ISSUE TITLE
请问这个 repo 目的是用 github 充当图床吗

### ISSUE THREAD

**Issue by KHLFYY** [WTP016-CN/Image_for_Blog#1]
请问这个 repo 目的是用 github 充当博客的图床吗？如果是的话，为什么不找个免费图床呢。这个加载速度应该会很感人吧……

**Comment by WTP016-CN** [comment]
使用的是与网宿合作的CDN jsdelivr CDN以加载图片
网宿是中国大陆第三大CDN提供商
